Re-architect project
There were some issues with how redirection was being handled. This
commit fixes most of the issues and removes some scripts. These removed
scripts can be added back or merged with the scripts added in this
commit.

diff --git a/rmgr_addfile b/rmgr_addfile
--- a/rmgr_addfile
+++ b/rmgr_addfile
@@ -3,8 +3,8 @@
 # Add a file corresponding to a database entry
 
 PrintUsage() {
-    cat 1>&2 << EOF
-Usage: $(basename $0) <bibkey> <file> <options>
+    cat << EOF
+Usage: $(basename $0) [<options>] <bibkey> <file>
 
 Copy the file corresponding to a BibTeX entry into the appropriate directory.
 
@@ -17,35 +17,66 @@ EOF
 
 source rmgr_setupenv
 
+if [ "$1" = "-d" ]; then
+    delete="yes"
+    shift
+else
+    delete="no"
+fi
+
 key="$1"
 [ -z "$key" ] && PrintUsage && exit 1
 file="$2"
-[ -z "$file" ] && PrintUsage && exit 1
-[ "$3" = "-d" ] && delete="yes" || delete="no"
+[ ! -f "$file" ] && PrintUsage && exit 1
 
-rmgr_searchkey "$key" && echo "Key not found." && exit 1
+searchResults=$(rmgr_lookupkey "$key")
+case $? in
+    0) ;;
+    1) echo "Key $key not found." && exit 1 ;;
+    2)
+        echo "Multiple keys found matching $key:"
+        rmgr_key2bib "$key"
+        exit 2
+        ;;
+    *) echo "Unknown exit code received from rmgr_lookupkey." && exit 70
+esac
 
-case $(rmgr_extracttype "$key") in
+case $(rmgr_key2bib "$key" | bib2type) in
     "article") dest="$ARTICLES" ;;
     "book") dest="$BOOKS" ;;
     *"thesis"*) dest="$THESES" ;;
-    *) dest="$ARTICLES" ;;
+    *) echo No destination set for type $(rmgr_extracttype "$key"). && exit
 esac
 if [ ! -d "$dest" ]; then
-    mkdir -p "$dest"
-    [ "$?" -ne 0 ] && echo "Error creating $dest." && exit 11
+    if  ! mkdir -p "$dest"; then
+        echo "Error creating $dest."
+        exit 11
+    fi
 fi
 
 newFilename=$(echo "$key" | tr '-' '_')
 extension=${file##*.}
 dest="$dest/$newFilename.$extension"
-[ -f "$dest" ] &&\
-    read -p "Destination ($dest) already exists. Still copy? [y|N]: " confirmation ||\
+if [ -f "$dest" ]; then
+    while true; do
+        read -p "Destination ($dest) already exists. Still copy? [y|q]: " confirmation
+        case "$confirmation" in
+            "y") break ;;
+            "q") exit 12 ;;
+        esac
+    done
+else
     confirmation="y"
+fi
 [ "$confirmation" = "y" ] && cp -f "$file" "$dest"
-[ "$delete" = "yes" ] && rm "$file"
+
+read -p 'Enter reading folder (or leave empty): ' readingFolder
 
 # Update the appropriate db fields
 rmgr_updval "$key" "date_updated" $(date "+%Y-%m-%d %H:%M:%S %Z %:::z")
 rmgr_updval "$key" "read_status" "unread"
-rmgr_updval "$key" "reading_folder"
+[ ! -z "$readingFolder" ] && rmgr_updval "$key" "reading_folder" "$readingFolder"
+
+[ "$delete" = "yes" ] && rm "$file"
+
+exit 0
diff --git a/rmgr_updval b/rmgr_updval
--- a/rmgr_updval
+++ b/rmgr_updval
@@ -3,11 +3,10 @@
 # Update a specific dict value for a key
 
 PrintUsage() {
-    cat 1>&2 << EOF
-Usage: $(basename $0) <bibkey> <datakey> [<val>]
+    cat << EOF
+Usage: $(basename $0) <bibkey> <datakey> <val>
 
-Update a specific datakey value for a specific bibkey. If val is not provided,
-it is asked for interactively.
+Update a specific datakey value for a specific bibkey.
 EOF
 }
 
@@ -20,33 +19,23 @@ key="$1"
 datakey="$2"
 [ -z "$datakey" ] && PrintUsage && exit 1
 val="$3"
+[ -z "$val" ] && PrintUsage && exit 1
 
 # Verify that the record exists
-searchResults=$(rmgr_searchkey "$key")
-[ -z "$searchResults" ] && echo "Key doesn't exist." && exit 2
+searchResults=$(rmgr_lookupkey "$key")
+case $? in
+    0) ;;
+    1) echo "Key $key not found." && exit 1 ;;
+    2)
+        echo "Multiple keys found matching $key:"
+        rmgr_key2bib "$key"
+        exit 2
+        ;;
+    *) echo "Unknown exit code recieved from rmgr_lookupkey." && exit 70
+esac
 
-# Print the current datakey value
-currentVal=$(sed -n "/^- $key:/,/^- / p" "$EXT" | grep "^  - $datakey:" | sed 's/^  - //')
-[ -z "$currentVal" ] && echo "Datakey ($datakey) not found." && exit 3
-echo "Current value for $currentVal"
-echo
+# Check if the key exists
+searchResults=$(sed -n "/^- $key:/,/^- / p" "$EXT" | grep "^  - $datakey:")
+[ -z "$searchResults" ] && echo "Datakey $datakey not found." && exit 3
 
-# Get the new value
-[ -z "$val" ] && read -p "New value: " val
-
-# Create a temp file for atomic editing
-tmpfile=$(mktemp --tmpdir=/tmp/ rmgr_updlist_XXXXXX)
-
-# Write everything before the current key
-sed -n "0,/^- $key:/ p" "$EXT" | head -n -1 > $tmpfile
-# Write everything until the current key's datakey (excluding the datakey)
-sed -n "/^- $key:/,/^  - $datakey:/ p" "$EXT" | head -n -1 >> $tmpfile
-echo "  - $datakey: $val" >> $tmpfile
-# Write the rest of the current record
-sed -n "/^- $key/,/^- / p" "$EXT" | sed "/^- $key/,/^  - $datakey:/ d" | sed -nE "/^\s{0,2}- /,$ p" >> $tmpfile
-# Get the key after the current key
-nextKey=$(sed -n "/^- $key:/,/^- / p" "$EXT" | tail -n 1 | grep '^- ' | sed 's/^- //')
-[ ! -z "$nextKey" ] && sed -n "/^- $nextKey/,$ p" "$EXT" | tail -n +2 >> $tmpfile
-
-# Overwrite the db with the tmpfile
-mv "$tmpfile" "$EXT"
+sed -i "/^- $key/,/^- / s/$datakey:.*$/$datakey: $val/" "$EXT"
